# -*- coding: utf-8 -*-
"""data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EBkE82YL-n82JpuS97GREKVo6ohdhZaS
"""

import os
import pandas as pd
from datetime import datetime
from vnstock import Vnstock
import logging

# Thiết lập logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

VN30_TICKERS = [
    'ACB', 'BCM', 'BID', 'BVH', 'CTG', 'FPT', 'GAS', 'GVR', 'HDB', 'HPG',
    'KDH', 'MBB', 'MSN', 'MWG', 'NVL', 'PDR', 'PLX', 'POW', 'SAB', 'SHB',
    'SSB', 'SSI', 'STB', 'TCB', 'TPB', 'VCB', 'VHM', 'VIB', 'VIC', 'VNM'
]

def validate_date(date_text):
    try:
        datetime.strptime(date_text, "%Y-%m-%d")
        return True
    except ValueError:
        raise ValueError(f"Định dạng ngày không hợp lệ: {date_text}. Hãy dùng định dạng YYYY-MM-DD.")

def fetch_stock_data(symbol, start_date, end_date, source="VCI", interval="1D"):
    try:
        stock = Vnstock().stock(symbol=symbol, source=source)
        df = stock.quote.history(start=start_date, end=end_date, interval=interval)
        df['id'] = symbol
        if df.empty or df['close'].sum() == 0:
            logging.warning(f"{symbol} có dữ liệu rỗng hoặc không hợp lệ.")
            return None
        return df
    except Exception as e:
        logging.error(f"Lỗi khi tải dữ liệu cho {symbol}: {e}")
        return None

def fetch_vn30_data(start_date, end_date, out_path="data/vn30_data.csv", source="VCI", interval="1D"):
    # Kiểm tra đầu vào ngày tháng
    validate_date(start_date)
    validate_date(end_date)

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    data_all = []

    # Lấy dữ liệu chỉ số VN30
    logging.info("Đang tải dữ liệu chỉ số VN30...")
    vn30_index = fetch_stock_data("VN30", start_date, end_date, source, interval)
    if vn30_index is not None:
        data_all.append(vn30_index)

    # Lấy dữ liệu cho từng mã cổ phiếu
    for ticker in VN30_TICKERS:
        logging.info(f"Đang tải dữ liệu cho {ticker}...")
        df = fetch_stock_data(ticker, start_date, end_date, source, interval)
        if df is not None:
            data_all.append(df)

    # Kết hợp và xử lý
    if not data_all:
        raise RuntimeError("Không có dữ liệu nào được tải về.")

    df_all = pd.concat(data_all, ignore_index=True)
    df_all.dropna(subset=['open', 'high', 'low', 'close'], inplace=True)
    df_all.rename(columns={'time': 'date'}, inplace=True)
    df_all.to_csv(out_path, index=False)

    logging.info(f"Đã lưu dữ liệu tại: {out_path}")
    return df_all